name: "Build packages"

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.targets }}
    runs-on: ubuntu-latest

    env:
      RESTORE_BUILD_PROJECT: 'Jellyfin.Server/Jellyfin.Server.csproj'

    strategy:
      matrix:
        targets:
          - 'centos.amd64'
          - 'fedora.amd64'
          - 'debian.amd64'
          - 'debian.arm64'
          - 'debian.armhf'
          - 'ubuntu.amd64'
          - 'ubuntu.arm64'
          - 'ubuntu.armhf'
          - 'linux.amd64'
          - 'linux.amd64-musl'
          - 'linux.arm64'
          - 'linux.armhf'
          - 'windows.amd64'
          - 'macos'
          - 'portable'

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Get commit hash
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build intermediate containers for ${{ matrix.targets }}
        run: docker build -f deployment/Dockerfile.${{ matrix.targets }} -t jellyfin-server-${{ matrix.targets }} deployment

      - name: Run intermediate container for ${{ matrix.targets }}
        run: |
          docker run -v $(pwd)/deployment/dist:/dist -v $(pwd):/jellyfin -e IS_UNSTABLE="yes" \
          -e BUILD_ID=${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }} jellyfin-server-${{ matrix.targets }}

      - name: Deploy to repo.jellyfin.org
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'deployment/dist'
          ARGS: '-rltgoDzvO --delete'
          REMOTE_PORT: '22'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /srv/repository/incoming/azure/${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }}/${{ matrix.targets }}
        

